### ISSUE TITLE
liftover erroneously swap ref/alt for insertions

### ISSUE THREAD

**Issue by logust79** [freeseek/score#16]
Example:
Variants in GRCh37
> 7       101200669       .      A       AC    .     PASS    .
7       101200669       .      A       AG    .     PASS    .

After liftover to GRCh38
> chr7    101557388       .      AG      A,AC    .     PASS    SWAP=-1
chr7    101557388       .      AG      A       .     PASS    SWAP=1

It should be:
> chr7    101557388       .      A      AC    .     PASS    .
chr7    101557388       .      A      AG       .     PASS    .

Command I run:
```
bcftools +liftover <grch37.vcf.gz> -- -s <GRCh37.ref.fa.gz> -f <GRCh38.ref.fa.gz> --reject rejected.vcf
```

**Comment by freeseek** [comment]
The problem is that you have three alleles at the locus, `AGGA`, `AGGGA`, and `ACGGA`, and GRCh37 and GRCh38 do not represent the same allele:
```
$ samtools faidx GRCh37.ref.fa.gz 7:101200669-101200672
>7:101200669-101200672
AGGA

$ samtools faidx GRCh38.ref.fa.gz chr7:101557388-101557392
>chr7:101557388-101557392
AGGGA
```
You can see what BCFtools/liftover does with the following commands:
```
$ (echo "##fileformat=VCFv4.2"; echo "##contig=<ID=7>"; echo -e "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO"; echo -e "7\t101200669\t.\tA\tAC\t.\t.\t."; echo -e "7\t101200669\t.\tA\tAG\t.\t.\t.") | bcftools +liftover -- -c hg19ToHg38.over.chain.gz -s GRCh37.ref.fa.gz | bcftools view -H
7	101200669	.	AG	ACG	.	.	.
7	101200669	.	AGGA	AGGGA	.	.	.

$ (echo "##fileformat=VCFv4.2"; echo "##contig=<ID=7>"; echo -e "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO"; echo -e "7\t101200669\t.\tA\tAC\t.\t.\t."; echo -e "7\t101200669\t.\tA\tAG\t.\t.\t.") | bcftools +liftover -- -c hg19ToHg38.over.chain.gz -s GRCh37.ref.fa.gz -f GRCh38.ref.fa.gz --no-left-align | bcftools view -H
chr7	101557388	.	AGG	AG,ACG	.	.	SWAP=-1
chr7	101557388	.	AGGGA	AGGA	.	.	SWAP=1
```
An alternative approach would be to first merge the two variants and then run BCFtools/liftover so that there is no need to add additional alleles:
```
$ (echo "##fileformat=VCFv4.2"; echo "##contig=<ID=7>"; echo -e "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO"; echo -e "7\t101200669\t.\tA\tAC\t.\t.\t."; echo -e "7\t101200669\t.\tA\tAG\t.\t.\t.") | bcftools norm -m+ | bcftools view -H
7	101200669	.	A	AC,AG	.	.	.

$ (echo "##fileformat=VCFv4.2"; echo "##contig=<ID=7>"; echo -e "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO"; echo -e "7\t101200669\t.\tA\tAC\t.\t.\t."; echo -e "7\t101200669\t.\tA\tAG\t.\t.\t.") | bcftools norm -m+ | bcftools +liftover -- -c hg19ToHg38.over.chain.gz -s GRCh37.ref.fa.gz -f GRCh38.ref.fa.gz | bcftools view -H
chr7	101557388	.	AG	AC,A	.	.	SWAP=2
```
In the latter scenario the `SWAP=2` INFO field indicates that the second alternate allele has become the reference allele

**Comment by logust79** [comment]
Thanks a lot for the quick response! I agree I'm the one being erroneous!
