### ISSUE TITLE
The liftover plugin cannot be run

### ISSUE THREAD

**Issue by wangzhennan14** [freeseek/score#24]
Hi,
I downloaded the stable version from https://software.broadinstitute.org/software/score/, then extracted it into the bin directory of bcftools-1.20, and added the BCFTOOLS_PLUGINS environment variable. When I run the "munge, score, metal, and blup" plugins, everything works fine. However, when trying to run the liftover plugin, it shows that the plugin cannot be found, even though the 'bcftools plugin -lv' command lists the plugin. I am using CentOS 7.
Could you help me resolve this issue? How can I run the liftover plugin successfully? Thank you.
Best wishes,
wang

**Comment by freeseek** [comment]
What is the stderr output of the following command?
```
bcftools +liftover
```
If you get an output like the following:
```
/usr/lib/x86_64-linux-gnu/bcftools/liftover.so:
	dlopen   .. /usr/lib/x86_64-linux-gnu/bcftools/liftover.so: cannot open shared object file: No such file or directory
liftover:
	dlopen   .. liftover: cannot open shared object file: No such file or directory

The bcftools plugin "liftover" was not found or is not functional. The environment variable BCFTOOLS_PLUGINS is not set
and no usable plugins were found in /usr/lib/x86_64-linux-gnu/bcftools.

Could not load "liftover".
```
What is then the output of the following command (making sure to replace with the path you get in your output)?
```
ls -l /usr/lib/x86_64-linux-gnu/bcftools/liftover.so
```

**Comment by wangzhennan14** [comment]
When I run `bcftools +liftover`, the output was `$ bcftools +liftover

About:   Run user defined plugin
Usage:   bcftools plugin <name> [OPTIONS] <file> [-- PLUGIN_OPTIONS]
         bcftools +name [OPTIONS] <file>  [-- PLUGIN_OPTIONS]

VCF input options:
   -e, --exclude EXPR             Exclude sites for which the expression is true
   -i, --include EXPR             Select sites for which the expression is true
   -r, --regions REGION           Restrict to comma-separated list of regions
   -R, --regions-file FILE        Restrict to regions listed in a file
        --regions-overlap 0|1|2   Include if POS in the region (0), record overlaps (1), variant overlaps (2) [1]
   -t, --targets REGION           Similar to -r but streams rather than index-jumps
   -T, --targets-file FILE        Similar to -R but streams rather than index-jumps
        --targets-overlap 0|1|2   Include if POS in the region (0), record overlaps (1), variant overlaps (2) [0]
VCF output options:
       --no-version               Do not append version and command line to the header
   -o, --output FILE              Write output to a file [standard output]
   -O, --output-type u|b|v|z[0-9] u/b: un/compressed BCF, v/z: un/compressed VCF, 0-9: compression level [v]
       --threads INTT             Use multithreading with <int> worker threads [0]
Plugin options:
   -h, --help                     List plugin's options
   -l, --list-plugins             List available plugins. See BCFTOOLS_PLUGINS environment variable and man page for details
   -v, --verbose                  Print verbose information, -vv increases verbosity
   -V, --version                  Print version string and exit
   -W, --write-index[=FMT]        Automatically index the output files [off]
`

**Comment by wangzhennan14** [comment]
When I run `bcftools +liftover`, the output as follow:
![error](https://github.com/user-attachments/assets/ef454056-5c8c-4d45-a3ff-f16da9e6b95e)

**Comment by freeseek** [comment]
So it looks like the plugin loaded just fine. What do you mean when you say that the plugin cannot be found? What happens if you run the following command?
```
bcftools +liftover -h
```

**Comment by wangzhennan14** [comment]
Hi,
Sorry，I run it successfully, thank you very much!
