### ISSUE TITLE
Single out of range variant causes program to exit

### ISSUE THREAD

**Issue by davmlaw** [freeseek/score#9]
A single record out of range (chr17 contig size is 83,257,441):

```
17      143074440       45      G       C       .       .       .
```

Expected:

* Record is written to reject file

Actual:

Entire program exits with message:

```
Unable to fetch sequence at 17:143074439-83257441
```

```
bcftools +liftover --version
```

Output:

```
bcftools  1.20-9-g4bd57e53 using htslib 1.20-4-gc93f5a57
plugin at 1.19 using htslib 1.20-4-gc93f5a57
```

**Workaround**

* preprocess VCF to ensure all variants are in range

**Comment by freeseek** [comment]
I can provide a better error message but is it more appropriate for the program to run over such a VCF or to break and let you know that you either have a broken VCF and/or you are providing the wrong fasta reference or chain file?

**Comment by davmlaw** [comment]
You have a good point in that potentially someone could mix up the VCF/references, which would be caught by the error.

In my case, it was historical hand typed data, which I should have pre-processed.

I have changed my mind and think catching the reference mixup is more important than not relying on people providing a valid VCF, so am happy to close the issue
